version: "3"

services:
  # 1. Master: ตัวควบคุมหลักของ Cluster
  spark-master:
    build: .
    container_name: spark-master
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    environment:
      - SPARK_MASTER_HOST=spark-master
      - SPARK_LOCAL_IP=0.0.0.0
    ports:
      - "8080:8080" # Web UI สำหรับดูสถานะ Cluster
      - "7077:7077" # พอร์ตสำหรับรับงานจาก Client

  # 2. Worker 1: เครื่องลูกข่ายเครื่องที่ 1 ที่ใช้ประมวลผลจริง
  spark-worker-1:
    build: .
    container_name: spark-worker-1
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    environment:
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=1g
      - SPARK_LOCAL_IP=0.0.0.0
    depends_on:
      - spark-master

  # 3. Worker 2: เครื่องลูกข่ายเครื่องที่ 2 เพิ่มพลังการประมวลผล
  spark-worker-2:
    build: .
    container_name: spark-worker-2
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    environment:
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=1g
      - SPARK_LOCAL_IP=0.0.0.0
    depends_on:
      - spark-master

  # 4. Client: เครื่องสำหรับส่ง Code (เช่น .py) เข้าไปรันใน Cluster
  spark-client:
    build: .
    container_name: spark-client
    depends_on:
      - spark-master
    volumes:
      - ./app:/app # เชื่อมโฟลเดอร์ app ในเครื่องเราเข้ากับคอนเทนเนอร์
    working_dir: /app
    command: tail -f /dev/null # เปิดเครื่องไว้ตลอดเวลาเพื่อรอรับคำสั่ง